version: "3.9"
services:
    web:
        build:
            context: .
            target: "web"
            labels:
                - "com.eltariel.dmrp.web"
        ports:
            - "${DMRP_WEB_PORT}:80"
        depends_on:
            - db
        volumes:
            - "${SHARED_DATA_ROOT}/${DMRP_DATA}:/dmrp"
        environment:
            CUSTOMCONNSTR_ProxyDataContext: "Server=db,1433;Initial Catalog=${DMRP_DB_NAME};Persist Security Info=False;User ID=sa;Password=${SQL_SA_PASSWORD};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"
            AppName: $DMRP_APP_NAME
            Discord__ClientId: "${DMRP_DISCORD_CLIENT_ID?err}"
            Discord__ClientSecret: "${DMRP_DISCORD_CLIENT_SECRET?err}"
            Discord__bot-token: "${DMRP_DISCORD_BOT_TOKEN?err}"
    bot:
        build:
            context: .
            target: "bot"
            labels:
                - "com.eltariel.dmrp.bot"
        depends_on:
            - db
        volumes:
            - "${SHARED_DATA_ROOT}/${DMRP_DATA}:/dmrp"
        environment:
            CUSTOMCONNSTR_ProxyDataContext: "Server=db,1433;Initial Catalog=${DMRP_DB_NAME};Persist Security Info=False;User ID=sa;Password=${SQL_SA_PASSWORD};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"
            Discord__bot-token: "${DMRP_DISCORD_BOT_TOKEN?err}"
            Discord__bot-url: "${DMRP_APP_URL?err}"
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        user: "1000:1000"
        ports:
            - "11433:1433"
        environment:
            SA_PASSWORD: "${SQL_SA_PASSWORD}"
            ACCEPT_EULA: "Y"
        volumes: 
          - "${SHARED_DATA_ROOT}/${SQL_DATA}:/var/opt/mssql"
